# Generated by Django 5.1.4 on 2025-01-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.png', help_text='Загрузите изображение для вашего профиля', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
