# Generated by Django 5.1.4 on 2025-01-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_size_list_category_total_sizes_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
        migrations.AddField(
            model_name='size',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='sizes', to='catalog.category', verbose_name='Категории'),
        ),
    ]
