# Generated by Django 5.1.4 on 2025-01-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_size_category_size_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seria',
            field=models.TextField(blank=True, default='Необозначен', null=True, verbose_name='Серия или номер продукта'),
        ),
    ]
