# Generated by Django 5.1.4 on 2025-01-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_seria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seria',
            field=models.CharField(blank=True, default='Необозначен', max_length=30, null=True, verbose_name='Серия или номер продукта'),
        ),
    ]
